# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from datetime import date, timedelta

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class FieldDict(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_datetime: AwareDatetime = Field(..., alias="_datetime")
    field_date: date = Field(..., alias="_date")
    field_timedelta: timedelta = Field(..., alias="_timedelta")
    field_int: int = Field(..., alias="_int")
    field_float: float = Field(..., alias="_float")
    field_str: str = Field(..., alias="_str")
    field_bool: bool = Field(..., alias="_bool")
    field_list: list[AwareDatetime] = Field(..., alias="_list")
    field_dict: FieldDict = Field(..., alias="_dict")
    field_name_that_is_long_with_multiple_lines: str
