# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class FieldDict(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key: str


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_datetime: str = Field(..., alias="_datetime")
    field_date: str = Field(..., alias="_date")
    field_timedelta: str = Field(..., alias="_timedelta")
    field_int: int = Field(..., alias="_int")
    field_float: float = Field(..., alias="_float")
    field_str: str = Field(..., alias="_str")
    field_bool: bool = Field(..., alias="_bool")
    field_list: list[str] = Field(..., alias="_list")
    field_dict: FieldDict = Field(..., alias="_dict")
    field_name_that_is_long_with_multiple_lines: str = Field(
        ...,
        alias="FieldNameThatIsLongWithMultipleLines",
    )
    mixed_numbers: list[int | float]
